### ISSUE TITLE
authentication token not provided

### ISSUE THREAD

**Issue by ayacoub1** [uzufly/showcase-cesium-ifc#2]
I am getting following error when trying to install npm:
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@uzufly/cesium-ifc-
viewer/0.11.0/75e0fd1d4673c5512996a8845b65328afad91655 - authentication token not provided

**Comment by matteo-pupa** [comment]
> I am getting following error when trying to install npm:
> npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@uzufly/cesium-ifc-
> viewer/0.11.0/75e0fd1d4673c5512996a8845b65328afad91655 - authentication token not provided

same!

**Comment by ted-dino** [comment]
any update guys? do we need to pay or do something to use the ifc-viewer package?

**Comment by mrestrepoj10** [comment]
@ted-dino Hi!! i'm having the same problem, can you please give detalis or share in how did you manage to make it work?

**Comment by ted-dino** [comment]
> @ted-dino Hi!! i'm having the same problem, can you please give detalis or share in how did you manage to make it work?

hey @mrestrepoj10 ! have you figured it out yet? for my case, i read and followed this [document](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-with-a-personal-access-token) and i also found this [helpful blog](https://www.codewalnut.com/tutorials/how-to-authenticate-github-cli-using-a-personal-access-token-pat) post  with a quick google search. i hope this helps!

**Comment by olange** [comment]
hi @ayacoub1, @matteo-pupa, @mrestrepoj10. I stumbled onto this issue in a cooldown cycle, while reviewing the PRs; sorry for the late answer.

You don't need to pay anything to use the [@uzufly/cesium-ifc-viewer](https://github.com/uzufly/exploratory) package: it was open-sourced, as part as a joint exploratory project with the [School of Architecture, Civil and Environmental Engineering (ENAC)](https://www.epfl.ch/schools/enac/) which is part of the EPFL.

As @ted-dino correctly pointed out, your _core issue_ is that we published the [@uzufly/cesium-ifc-viewer](https://github.com/uzufly/exploratory) in the GitHub Package Registry (GHP) instead of NPM.js default registry. And the GitHub Package Registry always [requires anyone to authenticate](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages), with its GitHub account — GHP requires this.

In short, to use the GHP, you need to:

1. [generate a Personal Access Token (PAT)](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic);
2. and configure your NPM local install to instruct NPM to:
  i. to lookup the GHR for any package in the **@uzufly** scope;
  ii. to use your PAT for that same scope.

One way to configure your NPM is to manually edit your `~/.npmrc`, in the following form:

```conf
//npm.pkg.github.com/:_authToken=‹YOUR_PERSONAL_ACCESS_TOKEN›
@uzufly:registry=https://npm.pkg.github.com/
```

Please note: I won't further support setting up your NPM environment; please figure it out. Note: ‹YOUR_PERSONAL_ACCESS_TOKEN› starts with `ghp_`.

I am pleased to see this experiment rose your interest and I owe you a more complete update about the status of this project. We should probably archive this repository, as it is not actively maintained.

**Comment by olange** [comment]
Again, thanks for your interest and sorry for the annoyance of the deployment on GHP.

Some background info

* We did not deploy on NPM.js, because this project is not meant for GA.
* It is a research project, we undertook on a spike of a week, to test whether we could integrate IFC with Cesium; we followed the path of creating an [IFCDataSource](https://github.com/uzufly/exploratory/blob/main/cesium-ifc-viewer/src/IFCDataSource.js).
* We nevertheless open-sourced the project for a code lab and the students of the EPFL/ENAC technical engineering school.
* We’re not actively monitoring this project; I will mark it as archived at a later time.

Status

* MVP quality.  Package was built during a hackathon: it worked, we shipped it, to showcase and collect feedback. Not intended for production use.
* Has some notable shortcomings — the most important being the mapping of the _spatial tree_ of the IFC file to the GLTF that is generated on the fly; also, it is a memory hog and IFC.js is completely outdated.

Features

* Drag & drop IFC file to import it;
* View the imported IFC model in the Cesium 3D canvas;
* Highlight IFC model parts on mouse hover;
* Tooltip with level and category names, while hovering model parts;
* Pick a model part (only shows Cesium's InfoBox with its ID so far).

Future work

* We have extensively evolved the ‹Cesium Viewer› web component, if this is the thing you’re interested in;
* We’re considering alternatives for importing IFC files in Cesium, one of which is to try again with the latest version of IFC.js; but there are other ones, the field has also evolved quite a bit since last year.

Would you be interested in knowing more, please reach out to me or start a discussion here; I would love to hear what you were expecting from this experiment:
https://github.com/uzufly/showcase-cesium-ifc/discussions
